Update assignment3.yml

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -1,8 +1,7 @@
 name: assignment3
 
 on:
-  push:
-    branches: [ main ]
+  push
 
 jobs:
   build:
@@ -11,11 +10,15 @@ jobs:
     - uses: actions/checkout@v2
     - name: Build image
       run: |
-        docker build -t books-service .
         echo "$(date -Iminutes)" > log.txt
-        echo "Student Name1, Student Name2" >> log.txt
-        echo "image successfully built" >> log.txt
-    - uses: actions/upload-artifact@v4
+        echo "Oren Savich, Itay Tiomkin" >> log.txt
+        docker build -t books-service .
+        if [ $? -eq 0 ]; then
+          echo "image successfully built" >> log.txt
+        else
+          echo "image not able to be built" >> log.txt
+        fi
+    - uses: actions/upload-artifact@v2
       with:
         name: log-file
         path: log.txt
@@ -28,17 +31,25 @@ jobs:
     - name: Set up Docker Compose
       run: |
         docker-compose up -d
-        echo "Container up and running" >> log.txt
+        if [ $? -eq 0 ]; then
+          echo "Container up and running" >> log.txt
+        else
+          echo "Container failed to run" >> log.txt
+        fi
     - name: Run tests
       run: |
         pip install pytest requests
         pytest -v tests/assn3_tests.py > assn3_test_results.txt
-        echo "tests succeeded" >> log.txt
-    - uses: actions/upload-artifact@v4
+        if [ $? -eq 0 ]; then
+          echo "tests succeeded" >> log.txt
+        else
+          echo "tests failed" >> log.txt
+        fi
+    - uses: actions/upload-artifact@v2
       with:
         name: test-results
         path: assn3_test_results.txt
-    - uses: actions/upload-artifact@v4
+    - uses: actions/upload-artifact@v2
       with:
         name: log-file
         path: log.txt
@@ -52,8 +63,15 @@ jobs:
       run: docker-compose up -d
     - name: Execute queries
       run: |
-        python query_job.py
-    - uses: actions/upload-artifact@v4
+        while IFS= read -r query; do
+          echo "Executing query: $query"
+          curl -X GET "http://localhost:5001/$query" -o response.txt
+          echo "Query: $query" >> query_log.txt
+          echo "Response:" >> query_log.txt
+          cat response.txt >> query_log.txt
+          echo "\n" >> query_log.txt
+        done < query.txt
+    - uses: actions/upload-artifact@v2
       with:
         name: query-results
-        path: response.txt
+        path: query_log.txt
